parameters:
    SUPABASE_URL: '%env(SUPABASE_URL)%'
    SUPABASE_KEY: '%env(SUPABASE_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\SupabaseService:
        arguments:
            $supabaseUrl: '%SUPABASE_URL%'
            $supabaseApiKey: '%SUPABASE_KEY%'
