# Utilise une image officielle PHP avec Apache
FROM php:8.2-apache

# Active les modules Apache et PHP nécessaires
RUN docker-php-ext-install pdo pdo_mysql && \
    a2enmod rewrite

# Installer Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Définir le répertoire de travail dans le bon sous-dossier
WORKDIR /var/www/html/brasserie_symfony

# Copier les fichiers du projet Symfony (situés dans brasserie_symfony)
COPY brasserie_symfony/ /var/www/html/brasserie_symfony/

# Donner les bons droits
RUN mkdir -p var && \
    chown -R www-data:www-data . && \
    chmod -R 755 var

# Exposer le port 80
EXPOSE 80

# Lancer Apache en mode foreground
CMD ["apache2-foreground"]
